# Generated by Django 4.2.6 on 2023-10-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='img',
            new_name='hi',
        ),
    ]
