# Generated by Django 4.2.6 on 2023-10-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_blogs_hi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='hi',
            new_name='img',
        ),
    ]
