# Generated by Django 4.2.6 on 2023-10-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_internshio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Internshio',
            new_name='Internship',
        ),
    ]
