# Generated by Django 4.2.6 on 2023-10-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_internship_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
